### ISSUE TITLE
conv3 去掉了，但full connection没改过来

### ISSUE THREAD

**Issue by fzjcdt** [tz28/Chinese-number-gestures-recognition#1]
conv3 去掉了，但full connection没改过来，训练会出错。

**Comment by fzjcdt** [comment]
抱歉，昨天clone的，一个小时前已经改过来了，没看到。

**Comment by tz28** [comment]
没关系，我也是今天在博客上有人提醒，才改过来的。当时疏忽了，忘记改过来了。谢谢

**Comment by fzjcdt** [comment]
很棒的项目。有一点小建议，安卓端每次好像每次识别都需要重新加载模型，可以放到初始化里只加载一次。显示结果那里可以改成实时检测，效果更震撼。可以先提取手势轮廓，或根据肤色提取手势，再二值化，效果更好。

**Comment by tz28** [comment]
谢谢谢谢，你提的意见很好，提取手势轮廓，当时有考虑到，因为时间比较紧，就没来得及做，老实讲这是我当时一门课的project，其实也感谢老师，project不限定题目，让我能够自由发挥，哈哈。因为后面还要准备期末考试，实在没时间了，轮廓就没做。不过你的意见很cool，后面我会尝试做下。
