### ISSUE TITLE
识别率问题

### ISSUE THREAD

**Issue by yavana** [tz28/Chinese-number-gestures-recognition#2]
1.用博主model_2500的模型验证数据，错误的很多
2.我自己采集了几百张数据，石头剪刀布（0,2,5），扩充数据后训练了500轮，模型的识别错误依然很多。
请问博主你训练的模型正确率是多少。

**Comment by tz28** [comment]
> 1.用博主model_2500的模型验证数据，错误的很多
> 2.我自己采集了几百张数据，石头剪刀布（0,2,5），扩充数据后训练了500轮，模型的识别错误依然很多。
> 请问博主你训练的模型正确率是多少。

在PC上模型效果很好，在APP上效果确实一般，因为app上要缩放图片加上模型用的类似le-net5的模型。我正在改进，预计很快会公布第二版，性能会有很大的提升。
