### ISSUE TITLE
识别结果巨差

### ISSUE THREAD

**Issue by zhanglaplace** [tz28/Chinese-number-gestures-recognition#3]
你好，非常感谢你的开源项目。
本地调通了你的安卓项目，但是手机测试的时候准确率很低，基本上10张只能识别出1-3张。
图像看的都非常清晰，可能会是什么问题呢。

**Comment by tz28** [comment]
> 你好，非常感谢你的开源项目。
> 本地调通了你的安卓项目，但是手机测试的时候准确率很低，基本上10张只能识别出1-3张。
> 图像看的都非常清晰，可能会是什么问题呢。

您好，在手机上可能因为精度损失之类的，确实精度不如在pc上的。发生的主要原因有三个：1.训练集自己收集的几百张，其它全是数据增强的，效果肯定要打折扣，这一个应该是影响效果的最大原因。2.网络结构用的是类lenet-5的结构，已经非常老了，这个我目前已经正在用resnet-50来重构了。3.怀疑opencv的area interplation压缩函数和tf中的实现有差异。我目前正在重构新版本，预计性能会有所提升，到因为实习工作比较繁忙，所以进度进度比较慢，我尽力尽快上传新版本。

**Comment by zhanglaplace** [comment]
@tz28 多谢，期待，感觉可能是数据不够多样性的可能比较大

**Comment by tz28** [comment]
> @tz28 多谢，期待，感觉可能是数据不够多样性的可能比较大

是的，这个应该是主要原因。这个也没办法，现在也没有开源的数据集，目前也尝试在解决这个问题。

**Comment by leok0ng** [comment]
楼主你好 我现在在训练一个公开数据集效果很不好 由于硬件有限我想请你帮帮忙 可以支付酬劳 能加个QQ嘛 763467305
