### ISSUE TITLE
range() integer end argument expected, got float

### ISSUE THREAD

**Issue by LeonardNeverSmile** [tz28/Chinese-number-gestures-recognition#4]
`Traceback (most recent call last):
  File "cnn.py", line 181, in <module>
    cnn_model(X_train, y_train, X_test, y_test, 0.8, 1e-4, num_epochs=500, minibatch_size=16)
  File "cnn.py", line 152, in cnn_model
    minibatches = random_mini_batches(X_train, y_train, minibatch_size, seed)
  File "cnn.py", line 80, in random_mini_batches
    for k in range(0, num_complete_minibatches):
TypeError: range() integer end argument expected, got float.`

**Comment by tz28** [comment]
> `Traceback (most recent call last): File "cnn.py", line 181, in <module> cnn_model(X_train, y_train, X_test, y_test, 0.8, 1e-4, num_epochs=500, minibatch_size=16) File "cnn.py", line 152, in cnn_model minibatches = random_mini_batches(X_train, y_train, minibatch_size, seed) File "cnn.py", line 80, in random_mini_batches for k in range(0, num_complete_minibatches): TypeError: range() integer end argument expected, got float.`

你好，num_complete_minibatches这个参数你设置的是整数吗？
