### ISSUE TITLE
居然发现校友了，幸会

### ISSUE THREAD

**Issue by xuexiangjys** [tz28/Chinese-number-gestures-recognition#5]
最近也在研究人工智能，刚好看到了，试了一下，发现识别率不是很高

**Comment by tz28** [comment]
> 最近也在研究人工智能，刚好看到了，试了一下，发现识别率不是很高

识别率确实不是很高，一来是训练集数量实在太少，二来，网络结构是最原始的lenet-5类型的相对性能较差。三迁移到app上存在精读损失，在pc上测感觉识别率还不错。我有时间会优化下的。
