### ISSUE TITLE
识别效果非常差

### ISSUE THREAD

**Issue by gushenjie** [tz28/Chinese-number-gestures-recognition#7]
您好,首先很感谢您分享了该项目,但是目前我使用了android程序,发现识别准确率非常非常非常差,有没有办法在优化下？

**Comment by tz28** [comment]
你好，根据大家的反应，发现在pc上效果很好，android确实效果不尽人意，但是貌似达到非常非常非常差的地步哈。优化可以从以下几个方面入手：
1、目前怀疑迁移到android上模型存在一定损失，不过我看tf貌似已经更新了全新的tf mobile的接口，你可以参考官方文档，尝试用新的接口试试。
2、因为在pc端图像缩放的时候采用的插值方法是谷歌自家的 area interpolation（面积插值法），这个没有提供java版本，也不知道它具体怎么实现的，只在tf官网找到他介绍这个方法是说和OpenCV里的xxx插值方法一样，这也是手机端引入OpenCV的原因。但是我不确定是否是一样的，你可以找一张图片把pc端的矩阵打出来，然后把手机端也打出来看看是否是一致的。
3、模型层面，因为搭的是lenet-5，这个太老了，你可以尝试用用resnet系列的试试，或者VGG都可以。这个因为我过去半年一直在实习，无限加班，所以一直没有时间去做。现在在准备秋招，近期也没时间做，你可以试试。等我秋招完，我会更新模型的。
4、数据层面，因为没有公开的数据集，数据集是我自己采集的，也就采集了300多张，剩下的全是数据增强生成的。你可以采集更多的真实图片作为训练集，另外数据增强也可以采用GANs才试试。

**Comment by tz28** [comment]
> 您好,首先很感谢您分享了该项目,但是目前我使用了android程序,发现识别准确率非常非常非常差,有没有办法在优化下？

你好，根据大家的反应，发现在pc上效果很好，android确实效果不尽人意，但是貌似达到非常非常非常差的地步哈。优化可以从以下几个方面入手：
1、目前怀疑迁移到android上模型存在一定损失，不过我看tf貌似已经更新了全新的tf mobile的接口，你可以参考官方文档，尝试用新的接口试试。
2、因为在pc端图像缩放的时候采用的插值方法是谷歌自家的 area interpolation（面积插值法），这个没有提供java版本，也不知道它具体怎么实现的，只在tf官网找到他介绍这个方法是说和OpenCV里的xxx插值方法一样，这也是手机端引入OpenCV的原因。但是我不确定是否是一样的，你可以找一张图片把pc端的矩阵打出来，然后把手机端也打出来看看是否是一致的。
3、模型层面，因为搭的是lenet-5，这个太老了，你可以尝试用用resnet系列的试试，或者VGG都可以。这个因为我过去半年一直在实习，无限加班，所以一直没有时间去做。现在在准备秋招，近期也没时间做，你可以试试。等我秋招完，我会更新模型的。
4、数据层面，因为没有公开的数据集，数据集是我自己采集的，也就采集了300多张，剩下的全是数据增强生成的。你可以采集更多的真实图片作为训练集，另外数据增强也可以采用GANs才试试。
