### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:

### ISSUE THREAD

**Issue by 1217337794** [tz28/Chinese-number-gestures-recognition#8]
Traceback (most recent call last):
  File "C:/Desktop/ruanjiangongchen/Chinese-number-gestures-recognition-master/digital_gesture_recognition/load_model.py", line 97, in <module>
    parameters = load_parameters()
  File "C:/Desktop/ruanjiangongchen/Chinese-number-gestures-recognition-master/digital_gesture_recognition/load_model.py", line 21, in load_parameters
    saver.restore(sess, "model2500//./cnn_model.ckpt.meta")
  File "D:\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1528, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "D:\Anaconda\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 364, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "D:\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: model2500//. : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

ErrorCode:
	with tf.Session() as sess:
		saver.restore(sess, "model//./cnn_model.ckpt")
		# print(W_conv1.eval())
这里出错，文件下没有model文件夹及其他文件，请问怎么处理，如果方便，麻烦您回复，谢谢您

**Comment by tz28** [comment]
> Traceback (most recent call last):
> File "C:/Desktop/ruanjiangongchen/Chinese-number-gestures-recognition-master/digital_gesture_recognition/load_model.py", line 97, in 
> parameters = load_parameters()
> File "C:/Desktop/ruanjiangongchen/Chinese-number-gestures-recognition-master/digital_gesture_recognition/load_model.py", line 21, in load_parameters
> saver.restore(sess, "model2500//./cnn_model.ckpt.meta")
> File "D:\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1528, in restore
> if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
> File "D:\Anaconda\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 364, in checkpoint_exists
> if file_io.get_matching_files(pathname):
> File "D:\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
> for single_filename in filename
> File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: model2500//. : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
> ; No such process
> 
> ErrorCode:
> with tf.Session() as sess:
> saver.restore(sess, "model//./cnn_model.ckpt")
> # print(W_conv1.eval())
> 这里出错，文件下没有model文件夹及其他文件，请问怎么处理，如果方便，麻烦您回复，谢谢您

数据集给了，代码给了，model没有的话，自己可以训练个model，放到相应文件下。
